rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/cache/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/.tbs/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/commonlog/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/env/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/tbs/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/tbslog/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/tencent/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/TGPA/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/.fff
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/.system_android_l2
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/.vmppd
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/ca-bundle.pem
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/HANYCJLZOEUS_TOKEN2.dat
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/mvnkflyhi.dat
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/mvnkflyhi.dat
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/pdrod_afmqa.dat
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/CONTENT/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/Engine/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ActImageSaved/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Collision_Detection/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Demos/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownloadV3/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PandoraV2/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/pixuicache/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ShareImageDownload/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TextureConfig/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UGC/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/VideoDownload/
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/eifsCache1
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/eifsCache2
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/eifsCache3
rm -rf /storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/eifsCache5
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_cn.wsds.sdk.game.data
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_crashrecord
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_crashSight
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_msdk
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_tbs_64
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_textures
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_tga_live_plugin
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_turingdfp
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_turingfd
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/app_webview
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/cache
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/code_cache
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/databases
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/files
rm -rf /data/user/0/com.tencent.tmgp.pubgmhd/shared_prefs
echo -e "\033[41m 完成! \033[0m"
echo -e "\033[5;46;43;37m
           完成执行任务的时间为$RELEASE         \033[0m"